name: Build and Run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4.0.1
          with:
            check-latest: true
        - name: Build
          run: |
            sudo apt update && sudo apt -y install cmake gdb
            cmake -B build && cmake --build build
        - name: Build and run under gdb
          env:
            GODEBUG: "cgocheck=2"
          run: |
            go build -gcflags=all="-N -l" -o build/main main.go
            gdb -batch -ex "set startup-with-shell off" -ex "file build/main" -ex "run" -ex "t a a bt full" -ex "quit"
